version: 0.1

phases:
  pre_build:
    commands:
      - echo Installing packages
      - yarn install
  build:
    commands:
      - yarn build

artifacts:
  files:
    - '**/*'
  base-directory: build