version: 0.1

phases:
  pre_build:
    commands:
      - echo Installing packages
      - npm install
  build:
    commands:
      - npm build

artifacts:
  files:
    - '**/*'
  base-directory: build